/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as AuthenticatedEditGameIdRouteImport } from './routes/_authenticated/edit.$gameId'
import { Route as AuthenticatedHostSessionIdRouteImport } from './routes/_authenticated/host.$sessionId'
import { Route as OverlayBoardOverlayTokenRouteImport } from './routes/overlay/board.$overlayToken'
import { Route as OverlayBuzzerOverlayTokenRouteImport } from './routes/overlay/buzzer.$overlayToken'
import { Route as OverlayCombinedOverlayTokenRouteImport } from './routes/overlay/combined.$overlayToken'
import { Route as OverlayQueueOverlayTokenRouteImport } from './routes/overlay/queue.$overlayToken'
import { Route as OverlayScoresOverlayTokenRouteImport } from './routes/overlay/scores.$overlayToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditGameIdRoute = AuthenticatedEditGameIdRouteImport.update({
  id: '/edit/$gameId',
  path: '/edit/$gameId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostSessionIdRoute =
  AuthenticatedHostSessionIdRouteImport.update({
    id: '/host/$sessionId',
    path: '/host/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const OverlayBoardOverlayTokenRoute =
  OverlayBoardOverlayTokenRouteImport.update({
    id: '/overlay/board/$overlayToken',
    path: '/overlay/board/$overlayToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const OverlayBuzzerOverlayTokenRoute =
  OverlayBuzzerOverlayTokenRouteImport.update({
    id: '/overlay/buzzer/$overlayToken',
    path: '/overlay/buzzer/$overlayToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const OverlayCombinedOverlayTokenRoute =
  OverlayCombinedOverlayTokenRouteImport.update({
    id: '/overlay/combined/$overlayToken',
    path: '/overlay/combined/$overlayToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const OverlayQueueOverlayTokenRoute =
  OverlayQueueOverlayTokenRouteImport.update({
    id: '/overlay/queue/$overlayToken',
    path: '/overlay/queue/$overlayToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const OverlayScoresOverlayTokenRoute =
  OverlayScoresOverlayTokenRouteImport.update({
    id: '/overlay/scores/$overlayToken',
    path: '/overlay/scores/$overlayToken',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookie': typeof CookieRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/play/$code': typeof PlayCodeRoute
  '/edit/$gameId': typeof AuthenticatedEditGameIdRoute
  '/host/$sessionId': typeof AuthenticatedHostSessionIdRoute
  '/overlay/board/$overlayToken': typeof OverlayBoardOverlayTokenRoute
  '/overlay/buzzer/$overlayToken': typeof OverlayBuzzerOverlayTokenRoute
  '/overlay/combined/$overlayToken': typeof OverlayCombinedOverlayTokenRoute
  '/overlay/queue/$overlayToken': typeof OverlayQueueOverlayTokenRoute
  '/overlay/scores/$overlayToken': typeof OverlayScoresOverlayTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookie': typeof CookieRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/play/$code': typeof PlayCodeRoute
  '/edit/$gameId': typeof AuthenticatedEditGameIdRoute
  '/host/$sessionId': typeof AuthenticatedHostSessionIdRoute
  '/overlay/board/$overlayToken': typeof OverlayBoardOverlayTokenRoute
  '/overlay/buzzer/$overlayToken': typeof OverlayBuzzerOverlayTokenRoute
  '/overlay/combined/$overlayToken': typeof OverlayCombinedOverlayTokenRoute
  '/overlay/queue/$overlayToken': typeof OverlayQueueOverlayTokenRoute
  '/overlay/scores/$overlayToken': typeof OverlayScoresOverlayTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookie': typeof CookieRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/play/$code': typeof PlayCodeRoute
  '/_authenticated/edit/$gameId': typeof AuthenticatedEditGameIdRoute
  '/_authenticated/host/$sessionId': typeof AuthenticatedHostSessionIdRoute
  '/overlay/board/$overlayToken': typeof OverlayBoardOverlayTokenRoute
  '/overlay/buzzer/$overlayToken': typeof OverlayBuzzerOverlayTokenRoute
  '/overlay/combined/$overlayToken': typeof OverlayCombinedOverlayTokenRoute
  '/overlay/queue/$overlayToken': typeof OverlayQueueOverlayTokenRoute
  '/overlay/scores/$overlayToken': typeof OverlayScoresOverlayTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/studio'
    | '/play/$code'
    | '/edit/$gameId'
    | '/host/$sessionId'
    | '/overlay/board/$overlayToken'
    | '/overlay/buzzer/$overlayToken'
    | '/overlay/combined/$overlayToken'
    | '/overlay/queue/$overlayToken'
    | '/overlay/scores/$overlayToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/studio'
    | '/play/$code'
    | '/edit/$gameId'
    | '/host/$sessionId'
    | '/overlay/board/$overlayToken'
    | '/overlay/buzzer/$overlayToken'
    | '/overlay/combined/$overlayToken'
    | '/overlay/queue/$overlayToken'
    | '/overlay/scores/$overlayToken'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/_authenticated/studio'
    | '/play/$code'
    | '/_authenticated/edit/$gameId'
    | '/_authenticated/host/$sessionId'
    | '/overlay/board/$overlayToken'
    | '/overlay/buzzer/$overlayToken'
    | '/overlay/combined/$overlayToken'
    | '/overlay/queue/$overlayToken'
    | '/overlay/scores/$overlayToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookieRoute: typeof CookieRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  PlayCodeRoute: typeof PlayCodeRoute
  OverlayBoardOverlayTokenRoute: typeof OverlayBoardOverlayTokenRoute
  OverlayBuzzerOverlayTokenRoute: typeof OverlayBuzzerOverlayTokenRoute
  OverlayCombinedOverlayTokenRoute: typeof OverlayCombinedOverlayTokenRoute
  OverlayQueueOverlayTokenRoute: typeof OverlayQueueOverlayTokenRoute
  OverlayScoresOverlayTokenRoute: typeof OverlayScoresOverlayTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/edit/$gameId': {
      id: '/_authenticated/edit/$gameId'
      path: '/edit/$gameId'
      fullPath: '/edit/$gameId'
      preLoaderRoute: typeof AuthenticatedEditGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host/$sessionId': {
      id: '/_authenticated/host/$sessionId'
      path: '/host/$sessionId'
      fullPath: '/host/$sessionId'
      preLoaderRoute: typeof AuthenticatedHostSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/overlay/board/$overlayToken': {
      id: '/overlay/board/$overlayToken'
      path: '/overlay/board/$overlayToken'
      fullPath: '/overlay/board/$overlayToken'
      preLoaderRoute: typeof OverlayBoardOverlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/buzzer/$overlayToken': {
      id: '/overlay/buzzer/$overlayToken'
      path: '/overlay/buzzer/$overlayToken'
      fullPath: '/overlay/buzzer/$overlayToken'
      preLoaderRoute: typeof OverlayBuzzerOverlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/combined/$overlayToken': {
      id: '/overlay/combined/$overlayToken'
      path: '/overlay/combined/$overlayToken'
      fullPath: '/overlay/combined/$overlayToken'
      preLoaderRoute: typeof OverlayCombinedOverlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/queue/$overlayToken': {
      id: '/overlay/queue/$overlayToken'
      path: '/overlay/queue/$overlayToken'
      fullPath: '/overlay/queue/$overlayToken'
      preLoaderRoute: typeof OverlayQueueOverlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/scores/$overlayToken': {
      id: '/overlay/scores/$overlayToken'
      path: '/overlay/scores/$overlayToken'
      fullPath: '/overlay/scores/$overlayToken'
      preLoaderRoute: typeof OverlayScoresOverlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedEditGameIdRoute: typeof AuthenticatedEditGameIdRoute
  AuthenticatedHostSessionIdRoute: typeof AuthenticatedHostSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedEditGameIdRoute: AuthenticatedEditGameIdRoute,
  AuthenticatedHostSessionIdRoute: AuthenticatedHostSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookieRoute: CookieRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  PlayCodeRoute: PlayCodeRoute,
  OverlayBoardOverlayTokenRoute: OverlayBoardOverlayTokenRoute,
  OverlayBuzzerOverlayTokenRoute: OverlayBuzzerOverlayTokenRoute,
  OverlayCombinedOverlayTokenRoute: OverlayCombinedOverlayTokenRoute,
  OverlayQueueOverlayTokenRoute: OverlayQueueOverlayTokenRoute,
  OverlayScoresOverlayTokenRoute: OverlayScoresOverlayTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
