/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as AuthenticatedEditGameIdRouteImport } from './routes/_authenticated/edit.$gameId'
import { Route as AuthenticatedHostSessionIdRouteImport } from './routes/_authenticated/host.$sessionId'
import { Route as ObsBoardRouteImport } from './routes/obs/board'
import { Route as ObsQueueRouteImport } from './routes/obs/queue'
import { Route as ObsCombinedRouteImport } from './routes/obs/combined'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditGameIdRoute = AuthenticatedEditGameIdRouteImport.update({
  id: '/edit/$gameId',
  path: '/edit/$gameId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostSessionIdRoute =
  AuthenticatedHostSessionIdRouteImport.update({
    id: '/host/$sessionId',
    path: '/host/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ObsBoardRoute = ObsBoardRouteImport.update({
  id: '/obs/board',
  path: '/obs/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsQueueRoute = ObsQueueRouteImport.update({
  id: '/obs/queue',
  path: '/obs/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsCombinedRoute = ObsCombinedRouteImport.update({
  id: '/obs/combined',
  path: '/obs/combined',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/play/$code': typeof PlayCodeRoute
  '/edit/$gameId': typeof AuthenticatedEditGameIdRoute
  '/host/$sessionId': typeof AuthenticatedHostSessionIdRoute
  '/obs/board': typeof ObsBoardRoute
  '/obs/queue': typeof ObsQueueRoute
  '/obs/combined': typeof ObsCombinedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/play/$code': typeof PlayCodeRoute
  '/edit/$gameId': typeof AuthenticatedEditGameIdRoute
  '/host/$sessionId': typeof AuthenticatedHostSessionIdRoute
  '/obs/board': typeof ObsBoardRoute
  '/obs/queue': typeof ObsQueueRoute
  '/obs/combined': typeof ObsCombinedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/play/$code': typeof PlayCodeRoute
  '/_authenticated/edit/$gameId': typeof AuthenticatedEditGameIdRoute
  '/_authenticated/host/$sessionId': typeof AuthenticatedHostSessionIdRoute
  '/obs/board': typeof ObsBoardRoute
  '/obs/queue': typeof ObsQueueRoute
  '/obs/combined': typeof ObsCombinedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/studio'
    | '/play/$code'
    | '/edit/$gameId'
    | '/host/$sessionId'
    | '/obs/board'
    | '/obs/queue'
    | '/obs/combined'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/studio'
    | '/play/$code'
    | '/edit/$gameId'
    | '/host/$sessionId'
    | '/obs/board'
    | '/obs/queue'
    | '/obs/combined'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/studio'
    | '/play/$code'
    | '/_authenticated/edit/$gameId'
    | '/_authenticated/host/$sessionId'
    | '/obs/board'
    | '/obs/queue'
    | '/obs/combined'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlayCodeRoute: typeof PlayCodeRoute
  ObsBoardRoute: typeof ObsBoardRoute
  ObsQueueRoute: typeof ObsQueueRoute
  ObsCombinedRoute: typeof ObsCombinedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/edit/$gameId': {
      id: '/_authenticated/edit/$gameId'
      path: '/edit/$gameId'
      fullPath: '/edit/$gameId'
      preLoaderRoute: typeof AuthenticatedEditGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host/$sessionId': {
      id: '/_authenticated/host/$sessionId'
      path: '/host/$sessionId'
      fullPath: '/host/$sessionId'
      preLoaderRoute: typeof AuthenticatedHostSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/obs/board': {
      id: '/obs/board'
      path: '/obs/board'
      fullPath: '/obs/board'
      preLoaderRoute: typeof ObsBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs/queue': {
      id: '/obs/queue'
      path: '/obs/queue'
      fullPath: '/obs/queue'
      preLoaderRoute: typeof ObsQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs/combined': {
      id: '/obs/combined'
      path: '/obs/combined'
      fullPath: '/obs/combined'
      preLoaderRoute: typeof ObsCombinedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedEditGameIdRoute: typeof AuthenticatedEditGameIdRoute
  AuthenticatedHostSessionIdRoute: typeof AuthenticatedHostSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedEditGameIdRoute: AuthenticatedEditGameIdRoute,
  AuthenticatedHostSessionIdRoute: AuthenticatedHostSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlayCodeRoute: PlayCodeRoute,
  ObsBoardRoute: ObsBoardRoute,
  ObsQueueRoute: ObsQueueRoute,
  ObsCombinedRoute: ObsCombinedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
